# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_Dialog(object):

    def __init__(self):
        self.cost_center_model=None


    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setFixedSize(618, 385)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setSizeGripEnabled(False)
        self.gridLayout_7 = QtGui.QGridLayout(Dialog)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.RunButton = QtGui.QPushButton(self.tab)
        self.RunButton.setGeometry(QtCore.QRect(510, 170, 71, 41))
        self.RunButton.setStyleSheet(_fromUtf8("\n"
                                               ""))
        self.RunButton.setObjectName(_fromUtf8("RunButton"))
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(10, 170, 495, 167))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMouseTracking(False)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.toolButton_Weight = QtGui.QToolButton(self.tab)
        self.toolButton_Weight.setGeometry(QtCore.QRect(380, 89, 37, 18))
        self.toolButton_Weight.setObjectName(_fromUtf8("toolButton_Weight"))
        self.BCReportEdit_6 = QtGui.QLineEdit(self.tab)
        self.BCReportEdit_6.setGeometry(QtCore.QRect(136, 114, 231, 20))
        self.BCReportEdit_6.setObjectName(_fromUtf8("BCReportEdit_6"))
        self.LiRunlabel = QtGui.QLabel(self.tab)
        self.LiRunlabel.setGeometry(QtCore.QRect(10, 36, 96, 16))
        self.LiRunlabel.setObjectName(_fromUtf8("LiRunlabel"))
        self.WeightEdit = QtGui.QLineEdit(self.tab)
        self.WeightEdit.setGeometry(QtCore.QRect(136, 88, 231, 20))
        self.WeightEdit.setObjectName(_fromUtf8("WeightEdit"))
        self.label_Weight = QtGui.QLabel(self.tab)
        self.label_Weight.setGeometry(QtCore.QRect(10, 88, 60, 16))
        self.label_Weight.setObjectName(_fromUtf8("label_Weight"))
        self.label_OutPath = QtGui.QLabel(self.tab)
        self.label_OutPath.setGeometry(QtCore.QRect(10, 140, 48, 16))
        self.label_OutPath.setObjectName(_fromUtf8("label_OutPath"))
        self.OutputPathEdit = QtGui.QLineEdit(self.tab)
        self.OutputPathEdit.setGeometry(QtCore.QRect(136, 141, 231, 20))
        self.OutputPathEdit.setObjectName(_fromUtf8("OutputPathEdit"))
        self.toolButton_ProjectQuery = QtGui.QToolButton(self.tab)
        self.toolButton_ProjectQuery.setGeometry(QtCore.QRect(380, 63, 37, 18))
        self.toolButton_ProjectQuery.setObjectName(_fromUtf8("toolButton_ProjectQuery"))
        self.label_ProjectQuery = QtGui.QLabel(self.tab)
        self.label_ProjectQuery.setGeometry(QtCore.QRect(10, 62, 120, 16))
        self.label_ProjectQuery.setObjectName(_fromUtf8("label_ProjectQuery"))
        self.TSlabel = QtGui.QLabel(self.tab)
        self.TSlabel.setGeometry(QtCore.QRect(10, 10, 102, 16))
        self.TSlabel.setObjectName(_fromUtf8("TSlabel"))
        self.toolButton_TS = QtGui.QToolButton(self.tab)
        self.toolButton_TS.setGeometry(QtCore.QRect(380, 11, 37, 18))
        self.toolButton_TS.setObjectName(_fromUtf8("toolButton_TS"))
        self.TimeSheetEdit = QtGui.QLineEdit(self.tab)
        self.TimeSheetEdit.setGeometry(QtCore.QRect(136, 10, 231, 20))
        self.TimeSheetEdit.setObjectName(_fromUtf8("TimeSheetEdit"))
        self.ProjectQueryEdit = QtGui.QLineEdit(self.tab)
        self.ProjectQueryEdit.setGeometry(QtCore.QRect(136, 62, 231, 20))
        self.ProjectQueryEdit.setObjectName(_fromUtf8("ProjectQueryEdit"))
        self.toolButton_Lirun = QtGui.QToolButton(self.tab)
        self.toolButton_Lirun.setGeometry(QtCore.QRect(380, 37, 37, 18))
        self.toolButton_Lirun.setObjectName(_fromUtf8("toolButton_Lirun"))
        self.WeigtSheetNameEdit = QtGui.QLineEdit(self.tab)
        self.WeigtSheetNameEdit.setGeometry(QtCore.QRect(508, 88, 81, 20))
        self.WeigtSheetNameEdit.setObjectName(_fromUtf8("WeigtSheetNameEdit"))
        self.label_WeightSheetName = QtGui.QLabel(self.tab)
        self.label_WeightSheetName.setGeometry(QtCore.QRect(433, 88, 66, 16))
        self.label_WeightSheetName.setMidLineWidth(0)
        self.label_WeightSheetName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WeightSheetName.setObjectName(_fromUtf8("label_WeightSheetName"))
        self.LiRunEdit_2 = QtGui.QLineEdit(self.tab)
        self.LiRunEdit_2.setGeometry(QtCore.QRect(136, 36, 231, 20))
        self.LiRunEdit_2.setObjectName(_fromUtf8("LiRunEdit_2"))
        self.label_BC = QtGui.QLabel(self.tab)
        self.label_BC.setGeometry(QtCore.QRect(10, 114, 60, 16))
        self.label_BC.setObjectName(_fromUtf8("label_BC"))
        self.BCSheetNameEdit = QtGui.QLineEdit(self.tab)
        self.BCSheetNameEdit.setGeometry(QtCore.QRect(508, 114, 81, 20))
        self.BCSheetNameEdit.setObjectName(_fromUtf8("BCSheetNameEdit"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(450, 10, 16, 16))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_NameOfBCSheet_2 = QtGui.QLabel(self.tab)
        self.label_NameOfBCSheet_2.setGeometry(QtCore.QRect(10, 169, 120, 16))
        self.label_NameOfBCSheet_2.setMidLineWidth(0)
        self.label_NameOfBCSheet_2.setText(_fromUtf8(""))
        self.label_NameOfBCSheet_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NameOfBCSheet_2.setObjectName(_fromUtf8("label_NameOfBCSheet_2"))
        self.ProfitSheetNameEdit = QtGui.QLineEdit(self.tab)
        self.ProfitSheetNameEdit.setGeometry(QtCore.QRect(508, 36, 81, 20))
        self.ProfitSheetNameEdit.setObjectName(_fromUtf8("ProfitSheetNameEdit"))
        self.label_TS_sheetname = QtGui.QLabel(self.tab)
        self.label_TS_sheetname.setGeometry(QtCore.QRect(433, 10, 66, 16))
        self.label_TS_sheetname.setMidLineWidth(0)
        self.label_TS_sheetname.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TS_sheetname.setObjectName(_fromUtf8("label_TS_sheetname"))
        self.ProjectQuerySheetNameEdit = QtGui.QLineEdit(self.tab)
        self.ProjectQuerySheetNameEdit.setGeometry(QtCore.QRect(508, 62, 81, 20))
        self.ProjectQuerySheetNameEdit.setObjectName(_fromUtf8("ProjectQuerySheetNameEdit"))
        self.label_BCSheetName = QtGui.QLabel(self.tab)
        self.label_BCSheetName.setGeometry(QtCore.QRect(433, 114, 66, 16))
        self.label_BCSheetName.setMidLineWidth(0)
        self.label_BCSheetName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BCSheetName.setObjectName(_fromUtf8("label_BCSheetName"))
        self.label_LiRunSheetName = QtGui.QLabel(self.tab)
        self.label_LiRunSheetName.setGeometry(QtCore.QRect(433, 36, 66, 16))
        self.label_LiRunSheetName.setMidLineWidth(0)
        self.label_LiRunSheetName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LiRunSheetName.setObjectName(_fromUtf8("label_LiRunSheetName"))
        self.toolButton_OutPath = QtGui.QToolButton(self.tab)
        self.toolButton_OutPath.setGeometry(QtCore.QRect(380, 140, 37, 18))
        self.toolButton_OutPath.setObjectName(_fromUtf8("toolButton_OutPath"))
        self.label_ProjectQuerySheetName = QtGui.QLabel(self.tab)
        self.label_ProjectQuerySheetName.setGeometry(QtCore.QRect(433, 62, 66, 16))
        self.label_ProjectQuerySheetName.setMidLineWidth(0)
        self.label_ProjectQuerySheetName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ProjectQuerySheetName.setObjectName(_fromUtf8("label_ProjectQuerySheetName"))
        self.toolButton_BC = QtGui.QToolButton(self.tab)
        self.toolButton_BC.setGeometry(QtCore.QRect(380, 115, 37, 18))
        self.toolButton_BC.setObjectName(_fromUtf8("toolButton_BC"))
        self.TSSheetNameEdit = QtGui.QLineEdit(self.tab)
        self.TSSheetNameEdit.setGeometry(QtCore.QRect(508, 10, 81, 20))
        self.TSSheetNameEdit.setText(_fromUtf8(""))
        self.TSSheetNameEdit.setDragEnabled(False)
        self.TSSheetNameEdit.setReadOnly(False)
        self.TSSheetNameEdit.setObjectName(_fromUtf8("TSSheetNameEdit"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(5, 5, 576, 171))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_costCenter_zh = QtGui.QLabel(self.groupBox)
        self.label_costCenter_zh.setGeometry(QtCore.QRect(280, 20, 54, 12))
        self.label_costCenter_zh.setObjectName(_fromUtf8("label_costCenter_zh"))
        self.label_costCenter_en = QtGui.QLabel(self.groupBox)
        self.label_costCenter_en.setGeometry(QtCore.QRect(280, 60, 54, 12))
        self.label_costCenter_en.setObjectName(_fromUtf8("label_costCenter_en"))
        self.lineEdit_costCenter_ZH = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_costCenter_ZH.setGeometry(QtCore.QRect(330, 20, 231, 20))
        self.lineEdit_costCenter_ZH.setObjectName(_fromUtf8("lineEdit_costCenter_ZH"))
        self.lineEdit_costCenter_EN = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_costCenter_EN.setGeometry(QtCore.QRect(330, 60, 231, 20))
        self.lineEdit_costCenter_EN.setObjectName(_fromUtf8("lineEdit_costCenter_EN"))
        self.pushButton_costCenter_add = QtGui.QPushButton(self.groupBox)
        self.pushButton_costCenter_add.setGeometry(QtCore.QRect(270, 110, 75, 23))
        self.pushButton_costCenter_add.setObjectName(_fromUtf8("pushButton_costCenter_add"))
        self.pushButton_costCenter_del = QtGui.QPushButton(self.groupBox)
        self.pushButton_costCenter_del.setGeometry(QtCore.QRect(370, 110, 75, 23))
        self.pushButton_costCenter_del.setObjectName(_fromUtf8("pushButton_costCenter_del"))
        self.tableView_costCenter = QtGui.QTableView(self.groupBox)
        self.tableView_costCenter.setGeometry(QtCore.QRect(10, 10, 251, 151))
        self.tableView_costCenter.setObjectName(_fromUtf8("tableView_costCenter"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(5, 180, 576, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_TS_costCenter_re = QtGui.QLabel(self.groupBox_2)
        self.label_TS_costCenter_re.setGeometry(QtCore.QRect(280, 20, 71, 16))
        self.label_TS_costCenter_re.setObjectName(_fromUtf8("label_TS_costCenter_re"))
        self.lineEdit_TS_costCenter_re = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_TS_costCenter_re.setGeometry(QtCore.QRect(360, 20, 201, 20))
        self.lineEdit_TS_costCenter_re.setObjectName(_fromUtf8("lineEdit_TS_costCenter_re"))
        self.pushButton_TS_costCenter_re_add = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_TS_costCenter_re_add.setGeometry(QtCore.QRect(280, 50, 75, 23))
        self.pushButton_TS_costCenter_re_add.setObjectName(_fromUtf8("pushButton_TS_costCenter_re_add"))
        self.pushButton_TS_costCenter_re_del = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_TS_costCenter_re_del.setGeometry(QtCore.QRect(380, 50, 75, 23))
        self.pushButton_TS_costCenter_re_del.setObjectName(_fromUtf8("pushButton_TS_costCenter_re_del"))
        self.tableView_costCenter_re = QtGui.QTableView(self.groupBox_2)
        self.tableView_costCenter_re.setGeometry(QtCore.QRect(10, 20, 256, 51))
        self.tableView_costCenter_re.setObjectName(_fromUtf8("tableView_costCenter_re"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(5, 260, 576, 80))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_exclude_pid = QtGui.QLabel(self.groupBox_3)
        self.label_exclude_pid.setGeometry(QtCore.QRect(280, 20, 71, 16))
        self.label_exclude_pid.setObjectName(_fromUtf8("label_exclude_pid"))
        self.lineEdit_exclude_pid = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_exclude_pid.setGeometry(QtCore.QRect(360, 20, 201, 20))
        self.lineEdit_exclude_pid.setObjectName(_fromUtf8("lineEdit_exclude_pid"))
        self.pushButton_exclude_pid_add = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_exclude_pid_add.setGeometry(QtCore.QRect(280, 50, 75, 23))
        self.pushButton_exclude_pid_add.setObjectName(_fromUtf8("pushButton_exclude_pid_add"))
        self.pushButton_exclude_pid_del = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_exclude_pid_del.setGeometry(QtCore.QRect(380, 50, 75, 23))
        self.pushButton_exclude_pid_del.setObjectName(_fromUtf8("pushButton_exclude_pid_del"))
        self.tableView_exclude_pid = QtGui.QTableView(self.groupBox_3)
        self.tableView_exclude_pid.setGeometry(QtCore.QRect(10, 20, 256, 51))
        self.tableView_exclude_pid.setObjectName(_fromUtf8("tableView_exclude_pid"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.tabWidget.raise_()

        self.show_cost_center_table()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "财务报表计算器", None))
        self.RunButton.setText(_translate("Dialog", "执行", None))
        self.toolButton_Weight.setText(_translate("Dialog", "...", None))
        self.BCReportEdit_6.setPlaceholderText(_translate("Dialog", "必填", None))
        self.LiRunlabel.setText(_translate("Dialog", "利润中心报表路径", None))
        self.WeightEdit.setPlaceholderText(_translate("Dialog", "选填", None))
        self.label_Weight.setText(_translate("Dialog", "权重表路径", None))
        self.label_OutPath.setText(_translate("Dialog", "输出路径", None))
        self.OutputPathEdit.setPlaceholderText(_translate("Dialog", "必填", None))
        self.toolButton_ProjectQuery.setText(_translate("Dialog", "...", None))
        self.label_ProjectQuery.setText(_translate("Dialog", "项目综合查询报表路径", None))
        self.TSlabel.setText(_translate("Dialog", "TimeSheet报表路径", None))
        self.toolButton_TS.setText(_translate("Dialog", "...", None))
        self.TimeSheetEdit.setPlaceholderText(_translate("Dialog", "必填", None))
        self.ProjectQueryEdit.setPlaceholderText(_translate("Dialog", "必填", None))
        self.toolButton_Lirun.setText(_translate("Dialog", "...", None))
        self.WeigtSheetNameEdit.setPlaceholderText(_translate("Dialog", "选填", None))
        self.label_WeightSheetName.setText(_translate("Dialog", "Sheet页名称", None))
        self.LiRunEdit_2.setPlaceholderText(_translate("Dialog", "必填", None))
        self.label_BC.setText(_translate("Dialog", "BC报表路径", None))
        self.BCSheetNameEdit.setPlaceholderText(_translate("Dialog", "选填", None))
        self.ProfitSheetNameEdit.setPlaceholderText(_translate("Dialog", "选填", None))
        self.label_TS_sheetname.setText(_translate("Dialog", "Sheet页名称", None))
        self.ProjectQuerySheetNameEdit.setPlaceholderText(_translate("Dialog", "选填", None))
        self.label_BCSheetName.setText(_translate("Dialog", "Sheet页名称", None))
        self.label_LiRunSheetName.setText(_translate("Dialog", "Sheet页名称", None))
        self.toolButton_OutPath.setText(_translate("Dialog", "...", None))
        self.label_ProjectQuerySheetName.setText(_translate("Dialog", "Sheet页名称", None))
        self.toolButton_BC.setText(_translate("Dialog", "...", None))
        self.TSSheetNameEdit.setPlaceholderText(_translate("Dialog", "选填", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "文件路径", None))
        self.groupBox.setTitle(_translate("Dialog", "成本中心", None))
        self.label_costCenter_zh.setText(_translate("Dialog", "中文：", None))
        self.label_costCenter_en.setText(_translate("Dialog", "英文：", None))
        self.pushButton_costCenter_add.setText(_translate("Dialog", "新增", None))
        self.pushButton_costCenter_del.setText(_translate("Dialog", "删除", None))
        self.groupBox_2.setTitle(_translate("Dialog", "待处理的TS中的具体部门名", None))
        self.label_TS_costCenter_re.setText(_translate("Dialog", "部门名称：", None))
        self.lineEdit_TS_costCenter_re.setPlaceholderText(_translate("Dialog", "支持正则表达式", None))
        self.pushButton_TS_costCenter_re_add.setText(_translate("Dialog", "新增", None))
        self.pushButton_TS_costCenter_re_del.setText(_translate("Dialog", "删除", None))
        self.groupBox_3.setTitle(_translate("Dialog", "不包含的项目ID", None))
        self.label_exclude_pid.setText(_translate("Dialog", "项目编号：", None))
        self.lineEdit_exclude_pid.setPlaceholderText(_translate("Dialog", "支持正则表达式", None))
        self.pushButton_exclude_pid_add.setText(_translate("Dialog", "新增", None))
        self.pushButton_exclude_pid_del.setText(_translate("Dialog", "删除", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "更多配置", None))

    def show_cost_center_table(self):
        self.cost_center_model = QtGui.QStandardItemModel()
        # 设置数据头栏名称
        self.cost_center_model.setHorizontalHeaderItem(0, QtGui.QStandardItem(u"中文"))
        self.cost_center_model.setHorizontalHeaderItem(1, QtGui.QStandardItem(u"英文缩写"))

        # 设置数据条目
        self.cost_center_model.setItem(0, 0, QtGui.QStandardItem(u"成都企业IT部"))
        self.cost_center_model.setItem(0, 1, QtGui.QStandardItem("cd"))

        self.cost_center_model.setItem(1, 0, QtGui.QStandardItem(u"深圳企业IT部"))
        self.cost_center_model.setItem(1, 1, QtGui.QStandardItem("sz"))

        self.cost_center_model.setItem(2, 0, QtGui.QStandardItem(u"西安企业IT部"))
        self.cost_center_model.setItem(2, 1, QtGui.QStandardItem("xa"))

        self.cost_center_model.setItem(3, 0, QtGui.QStandardItem(u"杭州企业IT部"))
        self.cost_center_model.setItem(3, 1, QtGui.QStandardItem("hz"))

        self.cost_center_model.setItem(4, 0, QtGui.QStandardItem(u"苏州企业IT部"))
        self.cost_center_model.setItem(4, 1, QtGui.QStandardItem("szhou"))

        self.cost_center_model.setItem(5, 0, QtGui.QStandardItem(u"南京企业IT部"))
        self.cost_center_model.setItem(5, 1, QtGui.QStandardItem("nj"))
        self.cost_center_model.setItem(6, 0, QtGui.QStandardItem(u"北京企业IT部"))
        self.cost_center_model.setItem(6, 1, QtGui.QStandardItem("bj"))

        # 将数据模型绑定到QTableView
        self.tableView_costCenter.setModel(self.cost_center_model)


    def get_cost_center_model(self):
        return self.cost_center_model

    # def set_cost_center_model_item(self,):


if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
